pipeline {
    agent any
    environment {
        REGISTRY = 'docker.io'
        REPO = 'kalaisk/kimai'
        IMAGE = "${REGISTRY}/${REPO}:${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/subadevanc/Kimai-TechForce.git'
            }
        }
        stage('Build') {
            steps {
                bat 'docker build -t %IMAGE% .'
            }
        }
        stage('Test') {
            steps {
                bat 'echo Running simulated tests...'
            }
        }
        stage('Push') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pat', variable: 'DOCKER_TOKEN')]) {
                    bat '''
                    echo %DOCKER_TOKEN% | docker login -u kalaisk --password-stdin
                    docker push %IMAGE%
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                bat 'echo Deploy step: manual or scripted deployment here.'
            }
        }
    }
}
