pipeline {
    agent any

    stages {
        stage('Build Image') {
            steps {
                dir('docker') {
                    bat 'docker build -t kalaisk/kimai-html:latest .'
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
               withCredentials([usernamePassword(credentialsId: 'docker-token', ...)]) {
                    bat 'echo %DOCKER_TOKEN% | docker login -u kalaisk --password-stdin'
                    bat 'docker push kalaisk/kimai-html:latest'
                }
            }
        }
    }
}
