pipeline {
    agent any

    environment {
        IMAGE_NAME = 'subadevanc/kimai'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        REMOTE_USER = 'ec2-user'
        REMOTE_HOST = '16.171.197.232'
        SSH_CRED_ID = 'ssh-key-id'
        DOCKER_CRED_ID = 'docker-hub-creds'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG ./docker'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Running simulated tests..."'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "$DOCKER_CRED_ID", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME:$IMAGE_TAG
                    """
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(credentials: ["$SSH_CRED_ID"]) {
                    sh """
                        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST '
                            docker pull $IMAGE_NAME:$IMAGE_TAG &&
                            docker stop kimai || true &&
                            docker rm kimai || true &&
                            docker run -d -p 8001:80 --name kimai $IMAGE_NAME:$IMAGE_TAG
                        '
                    """
                }
            }
        }
    }
}
